name: Verify Data

on: [push, pull_request]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby

        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Verify Conference Data
        run: bundle exec verify_data

      - name: Verify Meetups Data
        run: bundle exec verify_meetups
